QuantumLearn/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;

namespace QuantumLearn.Controllers
{
    public class LessonController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Num1()
        {
            // Info to send to view
            int lessonNum = 1;
            return View(lessonNum);
        }

        public IActionResult Num2()
        {
            int lessonNum = 2;
            return View(lessonNum);
        }

        public IActionResult Num3()
        {
            int lessonNum = 3;
            return View(lessonNum);
        }

        public IActionResult Num4()
        {
            int lessonNum = 4;
            return View(lessonNum);
        }

        public IActionResult Num5()
        {
            int lessonNum = 5;
            return View(lessonNum);
        }

        public IActionResult Num6()
        {
            int lessonNum = 6;
            return View(lessonNum);
        }

        public IActionResult Num7()
        {
            int lessonNum = 7;
            return View(lessonNum);
        }

        public IActionResult Num8()
        {
            int lessonNum = 8;
            return View(lessonNum);
        }

        public IActionResult Num9()
        {
            int lessonNum = 9;
            return View(lessonNum);
        }

        public IActionResult Num10()
        {
            int lessonNum = 10;
            return View(lessonNum);
        }

        public IActionResult Num11()
        {
            int lessonNum = 11;
            return View(lessonNum);
        }

        public IActionResult Num12()
        {
            int lessonNum = 12;
            return View(lessonNum);
        }

        public IActionResult Num13()
        {
            int lessonNum = 13;
            return View(lessonNum);
        }
    }
}

QuantumLearn/Views/Lesson/Index.cshtml
@{
    ViewData["Title"] = "Lessons";
}

<div>
    <h1 class="display-4 text-center" id="lessonsTitle">QuantumLearn Lessons</h1><br />

    <div class="container row row-cols-1 row-cols-md-3 g-4 justify-content-center h-100">
        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less1Main.jpg" class="img-fluid rounded-start lessonPic" alt="Quantum Computer">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num1" class="disguisedLink">Lesson 1</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num1" class="disguisedLink">History of Quantum Computers</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num1">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz1">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less2Main.jpg" class="img-fluid rounded-start lessonPic" alt="Desktop Computer">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num2" class="disguisedLink">Lesson 2</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num2" class="disguisedLink">Classical vs Quantum Computers</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num2">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz2">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less3Main.jpg" class="img-fluid rounded-start lessonPic" alt="Qubits">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num3" class="disguisedLink">Lesson 3</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num3" class="disguisedLink">Why Learn Quantum Computing</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num3">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz3">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less4Main.jpg" class="img-fluid rounded-start lessonPic" alt="Qubit">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num4" class="disguisedLink">Lesson 4</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num4" class="disguisedLink">Qubits, Superposition & Entanglement</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num4">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz4">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less5Main.jpg" class="img-fluid rounded-start lessonPic" alt="Square Root of Negative 1">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num5" class="disguisedLink">Lesson 5</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num5" class="disguisedLink">Imaginary Unit</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num5">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz5">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less6Main.jpg" class="img-fluid rounded-start lessonPic" alt="Qubit">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num6" class="disguisedLink">Lesson 6</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num6" class="disguisedLink">Qubit State</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num6">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz6">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less7Main.jpg" class="img-fluid rounded-start lessonPic" alt="Probabily Chart">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num7" class="disguisedLink">Lesson 7</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num7" class="disguisedLink">Probability</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num7">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz7">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less8Main.jpg" class="img-fluid rounded-start lessonPic" alt="Phase Chart">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num8" class="disguisedLink">Lesson 8</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num8" class="disguisedLink">Qubit Phase</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num8">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz8">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less9Main.jpg" class="img-fluid rounded-start lessonPic" alt="Amplitude Lines">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num9" class="disguisedLink">Lesson 9</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num9" class="disguisedLink">Qubit Amplitude</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num9">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz9">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less10Main.jpg" class="img-fluid rounded-start lessonPic" alt="Logic Gates">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num10" class="disguisedLink">Lesson 10</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num10" class="disguisedLink">Logic Gates</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num10">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz10">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less11Main.jpg" class="img-fluid rounded-start lessonPic" alt="Quantum Computer Chip">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num11" class="disguisedLink">Lesson 11</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num11" class="disguisedLink">Quantum Gates Overview</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num11">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz11">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less12Main.jpg" class="img-fluid rounded-start lessonPic" alt="Quantum Gates Applied to Qubits">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num12" class="disguisedLink">Lesson 12</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num12" class="disguisedLink">Common Quantum Gates</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num12">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz12">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-3 border-dark p-0 me-5 h-100">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="~/images/Less13Main.jpg" class="img-fluid rounded-start lessonPic" alt="3D Algorithm Visual">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="lessonNum"><a asp-controller="Lesson" asp-action="Num13" class="disguisedLink">Lesson 13</a></h5>
                        <p class="card-text lessonName"><a asp-controller="Lesson" asp-action="Num13" class="disguisedLink">Quantum Algorithms</a></p>
                        <p>
                            <a type="button" class="btn btn-success btn-sm" asp-controller="Lesson" asp-action="Num13">Start Lesson</a>
                            <a type="button" class="btn btn-warning btn-sm" asp-controller="Quiz" asp-action="Quiz13">Take Quiz</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QuantumLearn/Views/Lesson/Num1.cshtml
@model int
@* the model brings in the quiz number *@

@{
    ViewData["Title"] = $"Lesson {Model}";
}

<div class="container lessQuizNum col-10">
    <h3 class="lessQuizNum">Lesson @Model</h3>
    <h1 class="lessName">A Brief History of Quantum Computers</h1><br />
    <div class="row">
        <div class="col-2">
            <img class="w-100 h-50 mt-5 rounded-3 border border-dark border-3" src="~/images/less1_PeterShor.jpg" />
            <p class="text-center fst-italic">Peter Shor</p>
        </div>
        <div class="col-9 fs-5">
            <h5 class="fw-bold opacity-75">Conceptual Foundations (Early 20th Century)</h5>
            Quantum mechanics was developed, laying the theoretical groundwork for quantum computing.
            <br /><br />
            <h5 class="fw-bold opacity-75">Early Propositions (1980-1990s)</h5>
            Physicists like Paul Benioff, Richard Feynman, and David Deutsch proposed the concept of quantum computing.
            <br /><br />
            <h5 class="fw-bold opacity-75">First Physical Implementations (1990s-2000s)</h5>
            Various physical systems, such as trapped ions and superconducting circuits, were explored for implementing quantum bits.
            <br /><br />
        </div>
    </div>

    <div class="row">
        <div class="col-2">
            <img class="w-100 h-50 mt-5 rounded-3 border border-dark border-3" src="~/images/less1_IBMprocessor.jpg" />
            <p class="text-center fst-italic">IBM 127-Qubit Processor</p>
        </div>
        <div class="col-9 fs-5">
            <h5 class="fw-bold opacity-75">Shor's Algorithm (1994)</h5>
            Peter Shor developed an algorithm for factoring large numbers efficiently on a quantum computer, sparking major interest in quantum computing.
            <br /><br />
            <h5 class="fw-bold opacity-75">Error Correction and Fault Tolerance (1990s-Present)</h5>
            Quantum error correction codes and fault-tolerant protocols were developed, a crucial step towards building practical quantum computers.
            <br /><br />
            <h5 class="fw-bold opacity-75">Commercial Quantum Computing (2010s-Present)</h5>
            Companies like IBM, Google, and others started building quantum processors and providing cloud-based quantum computing services.
            <br /><br />
        </div>
    </div>

    <div class="row">
        <div class="col-2">
            <img class="w-100 h-50 mt-5 rounded-3 border border-dark border-3" src="~/images/less1_GoogQuantComp.jpg" />
            <p class="text-center fst-italic">Google's Quantum Computer</p>
        </div>
        <div class="col-9 fs-5">
            <h5 class="fw-bold opacity-75">Quantum Supremacy (2019)</h5>
            Google claimed "quantum supremacy" when their quantum computer solved a specific problem faster than a classical computer could. However, this didn't mean quantum computers were generally superior to classical ones as of that time.
            <br /><br />
            <h5 class="fw-bold opacity-75">Ongoing Developments (Present)</h5>
            Research in quantum computing is highly active, with ongoing efforts to increase the number of qubits, improve error rates, and develop useful quantum algorithms.
            <br /><hr />
            It's important to note that while classical computing has a long and well-established history, quantum computing is still in its early stages and much of its potential remains theoretical.
        </div>
    </div>

    @await Html.PartialAsync("_TakeQuizPrevNextButtons", Model)
</div>

QuantumLearn/Views/Lesson/Num10.cshtml
@model int

@{
    ViewData["Title"] = $"Lesson {Model}";
}

<div class="container lessQuizNum col-10">
    <h3 class="lessQuizNum">Lesson @Model</h3>
    <h1 class="lessName">Logic Gates</h1><br />

    <div class="row">
        <div class="col-9 fs-5">
            In classical computing, logic gates are the basic building blocks that perform certain operations on one or more bits of data.
            They are the simplest form of data processors and all digital systems are based on these gates.
            This review of classical gates will help with understanding quantum gates.
            <br /><hr />
            <h5 class="fw-bold opacity-75">Seven basic types of logic gates:</h5><br />
        </div>
    </div>

    <div class="row rowLess10">
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">1. NOT gate</h5>
            This gate has only one input and one output. The output is the opposite of the input: if you input 1, you get out 0, and vice versa.
        </div>
        <div class="col-3">
            <img class="w-100 h-75 rounded-3 border border-dark border-3" src="~/images/less10_NOT.jpg" />
            <p class="text-center fst-italic">NOT Symbol</p>
        </div>
    </div>

    <div class="row rowLess10">
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">2. AND gate</h5>
            This gate takes two inputs and gives an output of 1 if both inputs are 1, and 0 otherwise.
        </div>
        <div class="col-3">
            <img class="w-100 h-75 rounded-3 border border-dark border-3" src="~/images/less10_AND.jpg" />
            <p class="text-center fst-italic">AND Symbol</p>
        </div>
    </div>

    <div class="row rowLess10">
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">3. NAND gate</h5>
            This gate is the opposite of the AND gate. It gives an output of 0 only when both inputs are 1. In all other cases, it gives an output of 1.
            <br /><br />
        </div>
        <div class="col-3">
            <img class="w-100 h-75 rounded-3 border border-dark border-3" src="~/images/less10_NAND.jpg" />
            <p class="text-center fst-italic">NAND Symbol</p>
        </div>
    </div>

    <div class="row rowLess10">
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">4. OR gate</h5>
            This gate gives an output of 1 if at least one of the inputs is 1, and 0 otherwise.
        </div>
        <div class="col-3">
            <img class="w-100 h-75 rounded-3 border border-dark border-3" src="~/images/less10_OR.jpg" />
            <p class="text-center fst-italic">OR Symbol</p>
        </div>
    </div>

    <div class="row rowLess10">
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">5. NOR gate</h5>
            This gate is the opposite of the OR gate. It gives an output of 1 only when both inputs are 0. In all other cases, it gives an output of 0.

            <br /><br />
        </div>
        <div class="col-3">
            <img class="w-100 h-75 rounded-3 border border-dark border-3" src="~/images/less10_NOR.jpg" />
            <p class="text-center fst-italic">NOR Symbol</p>
        </div>
    </div>

    <div class="row rowLess10">
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">6. XOR gate (Exclusive OR)</h5>
            This gate gives an output of 1 only when the inputs are different (one input is 1 and the other is 0).

            <br /><br />
        </div>
        <div class="col-3">
            <img class="w-100 h-75 rounded-3 border border-dark border-3" src="~/images/less10_XOR.jpg" />
            <p class="text-center fst-italic">XOR Symbol</p>
        </div>
    </div>

    <div class="row rowLess10">
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">7. XNOR gate (Exclusive NOR)</h5>
            This gate gives an output of 1 when the inputs are the same (either both 1 or both 0).
            <br /><br />
        </div>
        <div class="col-3">
            <img class="w-100 h-75 rounded-3 border border-dark border-3" src="~/images/less10_XNOR.jpg" />
            <p class="text-center fst-italic">XNOR Symbol</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 fs-5">
            <img class="w-100 h-100 rounded-3 border border-dark border-3" src="~/images/less10_LogicGates.jpg" />
            <hr />
        </div>
    </div>

    <div class="row mt-5 justify-content-center text-center">
        <div class="col-9 fs-5">
            By combining these gates in various ways, you can build circuits that perform complex operations. This is the foundation of digital computing: all computer processors are made up of vast numbers of these gates.
        </div>
    </div>

    @await Html.PartialAsync("_TakeQuizPrevNextButtons", Model)
</div>

QuantumLearn/Views/Lesson/Num11.cshtml
@model int

@{
    ViewData["Title"] = $"Lesson {Model}";
}

<div class="container lessQuizNum col-10">
    <h3 class="lessQuizNum">Lesson @Model</h3>
    <h1 class="lessName">Quantum Gates Overview</h1><br />

    <div class="row">
        <div class="col-9 fs-5">
            Quantum gates are operations that can be applied to qubits to change their state. They are the building blocks of quantum computing, just like logic gates (AND, OR, NOT, etc.) are for classical computing.
            <br /><hr />
            <h5 class="fw-bold opacity-75">Here are some basic topics related to quantum gates:</h5><br />
        </div>
    </div>

    <div class="row">
        <div class="col-3">
            <img class="w-100 h-50 rounded-3 border border-dark border-3" src="~/images/less11_atomGIF.gif" />
        </div>
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">Unitary Operation</h5>
            Quantum gates perform a kind of operation called a "unitary operation." This operation changes the state of a qubit but preserves the probability of measuring different states. This is a fundamental requirement from quantum mechanics that distinguishes quantum gates from classical logic gates.
            <br /><br />
            <h5 class="fw-bold opacity-75">Reversibility</h5>
            Unlike classical gates, which sometimes erase information (for example, the AND gate gives 0 if any of its input bits are 0, so you can't recover the inputs from the output), quantum gates are reversible. This means if you apply a gate operation, you can always apply another gate to get back to your original state.
            <br /><br />
        </div>
    </div>

    <div class="row">
        <div class="col-3">
            <img class="w-100 h-25 mt-5 rounded-3 border border-dark border-3" src="~/images/less11_Circuit.jpg" />
            <p class="text-center fst-italic">A Simple Quantum Circuit</p>
        </div>
        <div class="col-8 fs-5">
            <h5 class="fw-bold opacity-75">Types of Gates</h5>
            There are different kinds of quantum gates. Some work on a single qubit, and some work on two or more qubits. Quantum gates are usually represented as matrices, because in quantum mechanics, states and operations can be represented mathematically as vectors and matrices. The next lesson will detail some common quantum gates.
            <br /><br />
            <h5 class="fw-bold opacity-75">Quantum Circuits</h5>
            Like classical computing, where you arrange logic gates in specific ways to build a useful circuit, you can arrange quantum gates in certain ways to build quantum circuits. These circuits can then perform complex quantum computations.
            <br /><hr />
            Remember, quantum gates operate under the principles of quantum mechanics, which are quite different from classical physics. This makes quantum computing a fascinating and complex field, but also quite challenging to fully grasp without a deep understanding of quantum mechanics.
        </div>
    </div>

    @await Html.PartialAsync("_TakeQuizPrevNextButtons", Model)
</div>
        

QuantumLearn/Views/Lesson/Num13.cshtml
@model int

@{
    ViewData["Title"] = $"Lesson {Model}";
}

<div class="container lessQuizNum col-10">
    <h3 class="lessQuizNum">Lesson @Model</h3>
    <h1 class="lessName">Quantum Algorithms</h1><br />

    <div class="row">
        <div class="col-11 fs-5">
            Quantum algorithms are a set of instructions that tell a quantum computer what to do. They're a special kind of algorithm designed to use the principles of quantum mechanics, including superposition, entanglement, and quantum interference, to solve certain types of problems much faster or more efficiently than classical algorithms.
            <br /><br />
            Unlike classical algorithms, where data is processed in a binary format (0s and 1s), quantum algorithms allow qubits to be in a superposition of states, perform computations on all possible states simultaneously, and then collapse to a single answer upon measurement.
            <br /><br /><hr />
            <p">Here are a couple famous quantum algorithms:</p>
        </div>
    </div>

    <div class="row">
        <div class="col-11 fs-5">
            <h5 class="fw-bold opacity-75">Shor's Algorithm</h5>
            Proposed by Peter Shor in 1994, this algorithm can factor large numbers exponentially faster than the best known classical algorithm. This has significant implications for cryptography, as most current cryptographic systems rely on the difficulty of factoring large numbers.<br /><br />
            <h5 class="fw-bold opacity-75">Grover's Algorithm</h5>
            Developed by Lov Grover in 1996, this algorithm can search an unsorted database much faster than any classical algorithm. Grover's algorithm quadratically reduces the number of steps needed to find a particular element in an unsorted list, compared to classical methods.<br /><br />
            These algorithms exploit the unique behavior of quantum mechanics to speed up computations, and they're some of the reasons why there's so much excitement around quantum computing.
            <br /><br /><hr />
            There are several simple quantum algorithms that showcase the unique principles of quantum computation. Here are a couple examples:
            <br /><br />
            <h5 class="fw-bold opacity-75">Deutsch's Algorithm</h5>
            This was the first example of a quantum algorithm that performs better than the best classical algorithm. It solves a simple problem: determining whether a function is balanced (outputs 0 half of the time and 1 half of the time) or constant (always outputs the same value). While a classical algorithm would need two queries to solve this problem with certainty, Deutsch's algorithm only needs one.<br /><br />
            <h5 class="fw-bold opacity-75">Bernstein-Vazirani Algorithm</h5>
            This algorithm solves a problem of finding a secret number hidden within a function. Classically, finding the number would require several steps proportional to the number of bits in the secret number, but the Bernstein-Vazirani algorithm can find it in just one step.<br /><br />
            Each of these algorithms highlights a unique aspect of quantum computation and demonstrates why quantum algorithms can be more efficient than classical algorithms. Despite their simplicity, understanding these algorithms requires a basic understanding of quantum computing concepts like superposition, entanglement, and quantum gates.
        </div>
    </div>

    @await Html.PartialAsync("_TakeQuizPrevNextButtons", Model)
</div>